#spring:
#  datasource:
#    url: jdbc:mysql://192.168.232.135:3306/userhub?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8999
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userhub?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Ks()^2552
    driver-class-name: com.mysql.cj.jdbc.Driver
